version: '3.7'
services:
  node-app:
    build: ./gate-simulator
    image: node-app:1.0
    container_name: node_container
    ports:
      - '9999:9999'
  mysql:
    image: mysql:8.0.18
    container_name: mysql_container
    command: --innodb_use_native_aio=0
    ports:
      - '3306:3306'
    volumes:
      - ./data_mysql:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
  postgres:
    image: postgres:12.0-alpine
    container_name: postgres_container
    ports:
      - '5432:5432'
    volumes:
      - ./data_pg:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=app
      - POSTGRES_DB=app
      - PGDATA=/tmp